# Generated by Django 4.0.6 on 2023-09-25 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('readonly', models.IntegerField(choices=[('1', 'Não Lido'), ('2', 'Lido')])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificacoes',
            },
        ),
    ]
