# Generated by Django 4.0.6 on 2023-09-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_notificacoes_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacoes',
            name='readonly',
            field=models.IntegerField(choices=[('1', 'Não Lido'), ('2', 'Lido')], default=1),
        ),
    ]
