# Generated by Django 4.0.6 on 2024-04-03 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('motivo_devolucao', models.TextField(blank=True, null=True)),
                ('tipo_projeto', models.IntegerField(choices=[(1, 'EFG'), (2, 'COTEC'), (3, 'CETT'), (4, 'BASILEU')])),
                ('data_solicitacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('prazo_entrega', models.DateField()),
                ('briefing', models.TextField()),
                ('prioridade', models.IntegerField(choices=[(1, 'NORMAL'), (2, 'URGENTE')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'A FAZER'), (2, 'FAZENDO'), (3, 'EM APROVAÇÃO'), (4, 'CONCLUÍDA')])),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solicitacoes',
            },
        ),
    ]
