# Generated by Django 4.0.6 on 2024-04-26 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('motivo_devolucao', models.TextField(blank=True, null=True)),
                ('tipo_projeto', models.IntegerField(choices=[(1, 'EFG'), (2, 'COTEC'), (3, 'CETT'), (4, 'BASILEU')])),
                ('data_solicitacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('prazo_entrega', models.DateField()),
                ('briefing', models.TextField()),
                ('prioridade', models.IntegerField(choices=[(1, 'NORMAL'), (2, 'URGENTE')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'A FAZER'), (2, 'FAZENDO'), (3, 'EM APROVAÇÃO'), (4, 'CONCLUÍDA')])),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solicitacoes',
            },
        ),
        migrations.CreateModel(
            name='Pastas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.solicitacoes')),
            ],
            options={
                'db_table': 'pastas',
            },
        ),
        migrations.CreateModel(
            name='Demandas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_designacao', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('prioridade', models.IntegerField(choices=[(1, 'Normal'), (2, 'Urgente')], default=1)),
                ('descricao_entrega', models.TextField(default='Nenhuma Descrição de Entrega')),
                ('data_entrega', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('devolutiva', models.TextField(default='')),
                ('status', models.IntegerField(choices=[(1, 'A Fazer'), (2, 'Fazendo'), (3, 'Em Aprovação'), (4, 'Concluído')])),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designante', to=settings.AUTH_USER_MODEL)),
                ('designante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pasta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.pastas')),
                ('solicitacao', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to='solicitacoes.solicitacoes')),
            ],
            options={
                'db_table': 'demandas',
            },
        ),
        migrations.CreateModel(
            name='Arquivos_Solicitacoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rota', models.TextField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.solicitacoes')),
            ],
            options={
                'db_table': 'arquivos_solicitacoes',
            },
        ),
        migrations.CreateModel(
            name='Arquivos_Demandas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rota', models.TextField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.demandas')),
            ],
            options={
                'db_table': 'arquivos_demandas',
            },
        ),
    ]
