# Generated by Django 4.0.6 on 2024-04-26 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoes',
            name='ultima_atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
