# Generated by Django 4.0.6 on 2024-04-03 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitacoes', '0002_pastas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demandas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_designacao', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('prioridade', models.IntegerField(choices=[(1, 'Normal'), (2, 'Urgente')], default=1)),
                ('descricao_entrega', models.TextField(default='Nenhuma Descrição de Entrega')),
                ('data_entrega', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('devolutiva', models.TextField(default='')),
                ('status', models.IntegerField(choices=[(1, 'A Fazer'), (2, 'Fazendo'), (3, 'Em Aprovação'), (4, 'Concluído')])),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designante', to=settings.AUTH_USER_MODEL)),
                ('designante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pasta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.pastas')),
            ],
            options={
                'db_table': 'demandas',
            },
        ),
    ]
