# Generated by Django 4.0.6 on 2024-04-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0003_alter_solicitacoes_ultima_atualizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoes',
            name='ultima_atualizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
