# Generated by Django 4.0.6 on 2024-04-04 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitacoes', '0003_demandas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivos_Solicitacoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rota', models.TextField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.solicitacoes')),
            ],
            options={
                'db_table': 'arquivos_solicitacoes',
            },
        ),
        migrations.CreateModel(
            name='Arquivos_Demandas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rota', models.TextField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.demandas')),
            ],
            options={
                'db_table': 'arquivos_demandas',
            },
        ),
    ]
