# Generated by Django 4.0.6 on 2024-04-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0004_alter_solicitacoes_ultima_atualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoes',
            name='gerencia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
