# Generated by Django 4.0.6 on 2024-04-05 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0004_arquivos_solicitacoes_arquivos_demandas'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandas',
            name='solicitacao',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.solicitacoes'),
        ),
    ]
