# Generated by Django 4.0.6 on 2024-04-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0005_solicitacoes_gerencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacoes',
            name='gerencia',
        ),
    ]
