# Generated by Django 4.0.6 on 2024-04-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0006_remove_solicitacoes_gerencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandas',
            name='gerencia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
