# Generated by Django 4.0.6 on 2024-04-05 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0007_alter_demandas_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='solicitacao',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to='solicitacoes.solicitacoes'),
        ),
    ]
