# Generated by Django 4.0.6 on 2023-12-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.IntegerField(choices=[(1, 'Gerente'), (2, 'Cordenador'), (3, 'Produtor'), (4, 'Redator'), (5, 'Designer'), (6, 'Externo')]),
        ),
    ]
