# Generated by Django 4.0.6 on 2023-12-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfil_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='und',
            field=models.IntegerField(choices=[(1, 'EFG'), (2, 'COTEC'), (3, 'CETT'), (4, 'BASILEU'), (5, 'Interno')], default=5),
        ),
    ]
