# Generated by Django 4.0.6 on 2023-12-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_perfil_und'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='und',
            field=models.IntegerField(choices=[(1, 'EFG'), (2, 'COTEC'), (3, 'CETT'), (4, 'BASILEU'), (5, 'INTERNO')], default=5),
        ),
    ]
